- name: check the number
  hosts: local
  connection: local
  vars_prompt:
  - name: nuymber
    prompt: enter the number
    private: false
  tasks:
  - name: print the given number is lessthan
    ansible.builtin.debug:
      msg: "the given number {{number}} is less than 10"
    when: number | int < 10

  - name: print the given number is greater than
    ansible.builtin.debug:
      msg: "the given number {{number}} is greaterthan or eqal to 10"
    when: number | int >= 10

