- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true

  - name: print user information
    ansible.builtin.debug:
      msg: "the user is: {{ USER }}"
