- name: installing packages
  hosts: [ web ]
  become: yes
  tasks:
  - name: installing
    ansible.builtin.packages:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - postfix
    - httpd
